services:
  test:
    profiles: [test]
    container_name: data-in-pipeline-test
    build:
      context: ..
      dockerfile: data-in-pipeline/Dockerfile
    volumes:
      - ..:/app
      # testcontainer
      # We need these lines to support running testcontainers in the container
      # Which needs access to the host docker
      - ${DOCKER_SOCKET_PATH:-/var/run/docker.sock}:/var/run/docker.sock
    user: root
    environment:
      # We use testcontainers to test postgres so this is needed
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
    # /testcontainers
    working_dir: /app
    command:
      [
        uv,
        run,
        --project,
        data-in-pipeline,
        pytest,
        data-in-pipeline,
        --color=yes,
        -v,
      ]
