name: Deploy backend-api to staging
on:
  workflow_dispatch: {}
  workflow_run:
    workflows: [CI/CD for backend-api]
    types:
      - completed
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy-backend-api-staging:
    defaults:
      run:
        working-directory: backend-api
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'}}
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v6

      - name: Configure AWS credentials (staging)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/navigator-backend-new-github-actions
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: eu-west-1

      - name: Login to Amazon ECR (staging)
        id: login-ecr-staging
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a

      - name: Build, tag, and push to ECR with commit hash and 'latest' tags (staging)
        id: build-image
        env:
          ECR_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          IMAGE_TAG: ${{ github.sha }}
          AWS_REGION: eu-west-1
          ECR_REPOSITORY: navigator-backend
        run: |
          docker tag navigator-backend $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag navigator-backend $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
