name: Deploy backend to production
on:
  workflow_dispatch: {}
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    defaults:
      run:
        working-directory: backend-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: make build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID_PRODUCTION }}:role/navigator-backend-new-github-actions
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr-production
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image-production
        env:
          ECR_REGISTRY: ${{ secrets.DOCKER_REGISTRY_PRODUCTION }}
          IMAGE_TAG: latest
          AWS_REGION: eu-west-1
          ECR_REPOSITORY: navigator-backend
        run: |
          docker tag navigator-backend $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
